from types import SimpleNamespace
import unittest

from data.postgres import placeholders, translate, PostgresConnection


class FakeConnection:
    """Tests transport semantics only; this is not a PostgreSQL execution test."""
    def __init__(self):
        self.info = SimpleNamespace(transaction_status=0)
        self.calls = []
        self.autocommit = False
    def execute(self, sql, params=()):
        self.calls.append((sql, params))
        if sql == "BEGIN":
            self.info.transaction_status = 2
        return SimpleNamespace(rowcount=1)
    def commit(self):
        self.calls.append(("COMMIT", ()))
        self.info.transaction_status = 0
    def rollback(self):
        self.calls.append(("ROLLBACK", ()))
        self.info.transaction_status = 0


class PostgresTransportTests(unittest.TestCase):
    def test_parameter_and_schema_translation_preserves_literals_and_precision(self):
        self.assertEqual(placeholders("SELECT '?' WHERE name=? AND x='it''s?'"), "SELECT '?' WHERE name=%s AND x='it''s?'")
        self.assertEqual(translate("INSERT OR IGNORE INTO x VALUES (?)"), "INSERT INTO x VALUES (%s) ON CONFLICT DO NOTHING")
        self.assertIn("DOUBLE PRECISION", translate("CREATE TABLE x (deadline REAL)"))
        self.assertIn("GENERATED BY DEFAULT", translate("CREATE TABLE x (id INTEGER PRIMARY KEY AUTOINCREMENT)"))

    def test_writer_lock_nested_transaction_commit_and_rollback(self):
        underlying = FakeConnection()
        connection = PostgresConnection(underlying)
        with connection:
            self.assertTrue(connection.in_transaction)
            with connection:
                connection.execute("BEGIN IMMEDIATE")
                connection.execute("SELECT ?", (1,))
            self.assertTrue(connection.in_transaction)
        self.assertEqual(sum(sql == "BEGIN" for sql, _ in underlying.calls), 1)
        self.assertEqual(sum("pg_advisory_xact_lock" in sql for sql, _ in underlying.calls), 1)
        self.assertEqual(underlying.calls[-1][0], "COMMIT")
        with self.assertRaises(ValueError):
            with connection:
                raise ValueError("transaction failure")
        self.assertEqual(underlying.calls[-1][0], "ROLLBACK")
        self.assertEqual(sum(sql == "BEGIN" for sql, _ in underlying.calls), 2)

    def test_snapshot_event_identity_advances_on_explicit_restore(self):
        underlying = FakeConnection()
        connection = PostgresConnection(underlying)
        connection.execute("INSERT INTO library_events VALUES (?,?,?,?,?)", (7, "family", "1.0.0", "event", "{}"))
        self.assertIn("setval", underlying.calls[-1][0])

    def test_metadata_queries_are_explicit_and_parameterized(self):
        underlying = FakeConnection()
        connection = PostgresConnection(underlying)
        connection.execute("PRAGMA table_info(library_versions)")
        self.assertIn("information_schema", underlying.calls[-1][0])
        self.assertEqual(underlying.calls[-1][1], ("library_versions",))
        with self.assertRaises(ValueError):
            connection.execute("PRAGMA unknown")


if __name__ == "__main__":
    unittest.main()
