"""Optional PostgreSQL transport for the existing metadata repositories.

The small SQL compatibility boundary covers repository-owned SQL only. Generated
task data cannot provide SQL. Writer transactions use one application advisory
lock, preserving existing read/modify/write semantics across connections.
"""
import re
from task_advisor.storage import Store


def placeholders(sql):
    """Convert qmark parameters while preserving SQL string literals."""
    result, quoted, index = [], False, 0
    while index < len(sql):
        char = sql[index]
        if char == "'":
            result.append(char)
            if quoted and index+1 < len(sql) and sql[index+1] == "'":
                result.append("'")
                index += 2
                continue
            quoted = not quoted
        else:
            result.append("%s" if char == "?" and not quoted else char)
        index += 1
    if quoted:
        raise ValueError("unterminated SQL literal")
    return "".join(result)


def translate(sql):
    result = placeholders(sql.strip())
    ignore = result.upper().startswith("INSERT OR IGNORE ")
    if ignore:
        result = re.sub(r"^INSERT OR IGNORE", "INSERT", result, flags=re.I)
        result = result.rstrip(";") + " ON CONFLICT DO NOTHING"
    result = re.sub(r"INTEGER PRIMARY KEY AUTOINCREMENT", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", result, flags=re.I)
    # SQLite REAL is binary64; PostgreSQL REAL is binary32. Preserve lease clocks.
    result = re.sub(r"\bREAL\b", "DOUBLE PRECISION", result, flags=re.I)
    return result


class PostgresConnection:
    def __init__(self, connection, *, writer_lock=739101):
        self.connection = connection
        self.writer_lock = writer_lock
        self.connection.autocommit = True
        self._contexts = []

    @property
    def in_transaction(self):
        return int(self.connection.info.transaction_status) != 0

    def begin(self):
        self.connection.execute("BEGIN")
        self.connection.execute("SELECT pg_advisory_xact_lock(%s)", (self.writer_lock,))

    def execute(self, sql, parameters=()):
        clean = sql.strip()
        if clean.upper() == "BEGIN IMMEDIATE":
            if not self.in_transaction:
                self.begin()
            return self.connection.execute("SELECT 1")
        if clean == "SELECT 1 FROM sqlite_master WHERE name='loop_records'":
            return self.connection.execute("SELECT 1 FROM pg_catalog.pg_tables WHERE schemaname=current_schema() AND tablename='loop_records'")
        pragma = re.fullmatch(r"PRAGMA table_info\(([a-z_]+)\)", clean)
        if pragma:
            return self.connection.execute("SELECT ordinal_position-1,column_name,data_type,is_nullable,column_default,NULL "
                "FROM information_schema.columns WHERE table_schema=current_schema() AND table_name=%s ORDER BY ordinal_position", (pragma[1],))
        if clean.upper().startswith("PRAGMA") or "sqlite_master" in clean:
            raise ValueError("unsupported SQLite-specific metadata operation")
        result = self.connection.execute(translate(clean), parameters)
        if re.match(r"INSERT INTO library_events VALUES", clean, flags=re.I):
            # Portable snapshots carry explicit event sequence IDs. Advance the
            # PostgreSQL identity so the next lifecycle event cannot collide.
            self.connection.execute("SELECT setval(pg_get_serial_sequence('library_events','sequence'), "
                                    "(SELECT MAX(sequence) FROM library_events), true)")
        return result

    def executescript(self, sql):
        with self:
            for statement in sql.split(";"):
                if statement.strip():
                    self.execute(statement)

    def __enter__(self):
        owns_transaction = not self.in_transaction
        if owns_transaction:
            self.begin()
        self._contexts.append(owns_transaction)
        return self

    def __exit__(self, kind, value, traceback):
        owns_transaction = self._contexts.pop()
        if owns_transaction:
            self.rollback() if kind is not None else self.commit()
        return False

    def commit(self):
        self.connection.commit()

    def rollback(self):
        self.connection.rollback()

    def close(self):
        self.connection.close()


class PostgresStore(Store):
    def __init__(self, dsn, *, connect=None, writer_lock=739101):
        if connect is None:
            try:
                import psycopg
            except ImportError as exc:
                raise RuntimeError("PostgreSQL mode requires the optional psycopg 3 package") from exc
            connect = psycopg.connect
        connection = PostgresConnection(connect(dsn, autocommit=True), writer_lock=writer_lock)
        try:
            super().__init__(connection=connection)
        except BaseException:
            connection.close()
            raise
